const rawJobs = [
      { id: 'j1', company: 'Mobile First Corp', position: 'React Native Developer', location: 'Remote', type: 'Full-time', salary: '$130k-175k', desc: 'Build cross-platform mobile applications using React Native. Work on products used by millions of users worldwide.', status: null },
      { id: 'j2', company: 'WebFlow Agency', position: 'Web Designer & Developer', location: 'Los Angeles, CA', type: 'Part-time', salary: '$80k-120k', desc: 'Create stunning web experiences for high-profile clients. Must have portfolio and experience with modern web design trends.', status: null },
      { id: 'j3', company: 'DataViz Solutions', position: 'Data Visualization Specialist', location: 'Boston, MA ', type: 'Full-time', salary: '$125k-165k', desc: 'Transform complex data into compelling visualizations. Required skills: D3.js, React, and strong analytical thinking.', status: null },
  { id: 'j8', company: 'CloudFirst Inc', position: 'Backend Developer', location: 'Seattle, WA', type: 'Full-time', salary: '$140k-190k', desc: 'Design and maintain scalable backend systems using Python and AWS. Work with modern DevOps practices and cloud infrastructure.', status: null },
      { id: 'j4', company: 'StartupXYZ', position: 'Full Stack Engineer', location: 'Remote', type: 'Full-time', salary: '$120k-160k', desc: 'Join our fast-growing startup and work on our core platform. Experience with Node.js and React required. Great benefits and equity package included.', status: null },
      { id: 'j5', company: 'TechCorp Industries', position: 'Senior Frontend Developer', location: 'San Francisco, CA', type: 'Full-time', salary: '$130k-175k', desc: 'We are looking for an experienced Frontend Developer to build scalable web applications using React and TypeScript. You will work with a talented team on cutting-edge projects.', status: null },
      { id: 'j6', company: 'Innovation Labs', position: 'UI/UX Engineer', location: 'Austin, TX', type: 'Full-time', salary: '$130k-175k', desc: 'Create beautiful and functional user interfaces for our suite of products. Strong design skills and frontend development expertise required.', status: null },
      { id: 'j7', company: 'MegaCorp Solutions', position: 'JavaScript Developer', location: 'New York, NY', type: 'Full-time', salary: '$130k-170k', desc: 'Build enterprise applications with JavaScript and modern frameworks. We offer competitive compensation, health insurance, and professional development opportunities.', status: null },
    
    ];